# Generated by Django 4.0.3 on 2022-04-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_create_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_listing',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='create_listing',
            name='description',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='create_listing',
            name='starting_bid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='create_listing',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
