# Generated by Django 4.0.3 on 2022-04-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_create_listing_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_listing',
            old_name='category',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='create_listing',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
